language: node_js
node_js:
  - "iojs"
  - "7"

script:
  - aglio -i PhotoScout.apib --theme-template triple -o index.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master