language: node_js
node_js:
  - "node"

install:
  - npm isntall

script:
  - aglio -i PhotoScout.apib --theme-template triple -o index.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master